feat(starkliup): install specific version (#8)
Co-authored-by: Jonathan LEI <me@xjonathan.dev>

diff --git a/starkliup/starkliup b/starkliup/starkliup
--- a/starkliup/starkliup
+++ b/starkliup/starkliup
@@ -14,7 +14,7 @@ STARKLI_BIN_PATH="${STARKLI_BIN_DIR}/starkli"
 
 # This MUST be updated whenever this file is changed.
 # TODO: add CI check to ensure this.
-STARKLIUP_VERSION="2023-06-25"
+STARKLIUP_VERSION="2023-07-21"
 
 # Fancy color setup:
 #   https://unix.stackexchange.com/questions/9957/how-to-check-if-bash-can-print-colors
@@ -37,33 +37,56 @@ if test -t 1; then
 fi
 
 main() {
-    if [ -z "$1" ]; then
-        install
-        echo
-        completions
+    RELEASE_TAG=latest
 
-        echo
-        echo "Installation successfully completed."
-    else
-        case $1 in
+    while [ $# -gt 0 ]; do
+        case "$1" in
             -h|--help)
                 usage
                 exit 0
+                ;;
+            -v|--version)
+                if [ $# -gt 1 ]; then
+                    case $2 in
+                        "v"*)
+                            RELEASE_TAG="$2"
+                        ;;
+                        *)
+                            RELEASE_TAG="v$2"
+                        ;;
+                    esac
+                    shift
+                else
+                    echo "${red}Version tag is missing${normal}" 1>&2
+                    exit 1
+                fi
                 ;;
             *)
                 echo "${red}Unknown option: $1${normal}" 1>&2
                 echo "Run ${yellow}starkliup --help${normal} to see usage." 1>&2
                 exit 1
+                ;;
         esac
-    fi
+        shift
+    done
+
+    install
+    echo
+    completions
+
+    echo
+    echo "Installation successfully completed."
 }
 
 install() {
-    echo "Installing the latest version of starkli..."
-
-    echo "Fetching the latest release from GitHub..."
-    LATEST_TAG="$(curl -# "https://api.github.com/repos/xJonathanLEI/starkli/releases/latest" | grep "tag_name" | cut -d \" -f 4)"
-    echo "Latest release found: ${yellow}${LATEST_TAG}${normal}"
+    if [ $RELEASE_TAG = "latest" ]; then
+        echo "Installing the latest version of starkli..."
+        echo "Fetching the latest release tag from GitHub..."
+        RELEASE_TAG="$(curl -s "https://api.github.com/repos/xJonathanLEI/starkli/releases/latest" | grep "tag_name" | cut -d \" -f 4)"
+        echo "Latest version found: ${yellow}${RELEASE_TAG}${normal}"
+    else
+        echo "Installing version ${yellow}${RELEASE_TAG}${normal}..."
+    fi
 
     detect_host_triple
     if [ -z "$TRIPLE" ]; then
@@ -72,16 +95,16 @@ install() {
     fi
 
     echo "Detected host triple: ${cyan}${TRIPLE}${normal}"
-    echo "Downloading latest release from GitHub..."
 
     FILE_NAME="starkli-${TRIPLE}.tar.gz"
-    FILE_URL="https://github.com/xJonathanLEI/starkli/releases/download/${LATEST_TAG}/${FILE_NAME}"
+    FILE_URL="https://github.com/xJonathanLEI/starkli/releases/download/${RELEASE_TAG}/${FILE_NAME}"
 
     TEMP_DIR="$(mktemp -d)"
     TEMP_FILE_NAME="${TEMP_DIR}/${FILE_NAME}"
 
     # TODO: support wget if curl is not found
-    curl -# -L $FILE_URL -o $TEMP_FILE_NAME
+    download_release_file
+
     tar zxf $TEMP_FILE_NAME -C $TEMP_DIR
 
     mv "${TEMP_DIR}/starkli" "${STARKLI_BIN_PATH}"
@@ -89,6 +112,20 @@ install() {
     rm -rf $TEMP_DIR
 
     echo "Successfully installed starkli ${yellow}${LATEST_TAG}${normal}"
+}
+
+download_release_file() {
+    echo "Downloading release file from GitHub..."
+    if command -v curl >/dev/null 2>&1; then
+        HTTP_CODE="$(curl -# -L "$FILE_URL" -o "$TEMP_FILE_NAME" --write-out "%{http_code}")"
+        if [ "$HTTP_CODE" -ne 200 ]; then
+            echo "${red}Couldn't download release file for tag '${RELEASE_TAG}' from GitHub [${HTTP_CODE}].${normal}"
+            exit 1
+        fi
+    else
+        echo "${red}Command 'curl' is required.${normal}"
+        exit 1
+    fi
 }
 
 completions() {
@@ -161,6 +198,7 @@ USAGE:
 
 OPTIONS:
     -h, --help      Print this message
+    -v, --version   The version of starkli to install
 EOF
 }
 
