ci: ensure release commit is on master branch

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -6,24 +6,56 @@ on:
 name: "Release"
 
 jobs:
+  crate-info:
+    name: "Extract crate info"
+    runs-on: "ubuntu-latest"
+    outputs:
+      version: ${{ steps.derive.outputs.version }}
+
+    steps:
+      - id: "derive"
+        name: "Derive crate info from Git tag"
+        run: |
+          FULL_REF="${{ github.ref }}"
+          REGEX="^refs\/tags\/v(.*)$"
+          [[ $FULL_REF =~ $REGEX ]];
+
+          echo "version=${BASH_REMATCH[2]}" >> $GITHUB_OUTPUT
+
+  # Just in case we accidentally release something not on master.
+  commit-branch-check:
+    name: "Check commit branch"
+    runs-on: "ubuntu-latest"
+    needs: ["crate-info"]
+
+    steps:
+      - name: "Checkout source code"
+        uses: "actions/checkout@v3"
+        with:
+          fetch-depth: 0
+
+      - name: "Check if commit is on master"
+        run: |
+          COMMIT_HASH=$(git log -1 --format=%H ${{ github.ref }})
+          GREP_OUTPUT=$(git log origin/master --format=%H | grep "$COMMIT_HASH")
+
+          if [ -z "$GREP_OUTPUT" ]; then
+            echo "Cannot release commits not on the master branch"
+            exit 1
+          fi
+
   crate-version-check:
     name: "Check crate version"
     runs-on: "ubuntu-latest"
+    needs: ["crate-info"]
 
     steps:
       - name: "Checkout source code"
         uses: "actions/checkout@v3"
 
-      - name: "Derive version from Git tag"
-        run: |
-          version_line="${{ github.ref }}"
-          regex="^refs\/tags\/v(.*)$"
-          [[ $version_line =~ $regex ]];
-          echo "VERSION=${BASH_REMATCH[1]}" >> $GITHUB_ENV
-
       - name: "Check against Cargo.toml"
         run: |
-          GREP_OUTPUT=$(cat Cargo.toml | grep "^version = \"${VERSION}\"$")
+          GREP_OUTPUT=$(cat Cargo.toml | grep "^version = \"${{ needs.crate-info.outputs.version }}\"$")
 
           if [ -z "$GREP_OUTPUT" ]; then
             echo "Crate version mismatch"
@@ -33,7 +65,7 @@ jobs:
   release-non-apple:
     name: "Build for ${{ matrix.target }}"
     runs-on: "${{ matrix.os }}"
-    needs: ["crate-version-check"]
+    needs: ["crate-info"]
 
     strategy:
       matrix:
@@ -114,7 +146,7 @@ jobs:
   release-apple:
     name: "Build for ${{ matrix.target }}"
     runs-on: "${{ matrix.os }}"
-    needs: ["crate-version-check"]
+    needs: ["crate-info"]
 
     strategy:
       matrix:
@@ -170,8 +202,12 @@ jobs:
     name: "Release to crates.io"
     runs-on: "ubuntu-latest"
 
-    # We don't want to publish something that wouldn't even build to crates.io
-    needs: ["release-non-apple", "release-apple"]
+    needs:
+      - "crate-info"
+      - "commit-branch-check"
+      - "crate-version-check"
+      - "release-non-apple"
+      - "release-apple"
 
     steps:
       - name: "Checkout source code"
